name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tii-px4-msgs-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PX4-msgs
        uses: actions/checkout@v3
        with:
          path: PX4-msgs
      - name: Run px4-msgs docker build
        run: |
          set -eux
          mkdir bin
          pushd PX4-msgs
          ./build.sh ../bin/
          popd
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: px4_msgs
          path: bin/*.deb
          retention-days: 1

  artifactory:
    runs-on: ubuntu-latest
    needs: tii-px4-msgs-deb
    if: github.event_name == 'push'
    steps:
      - name: Download builds
        uses: actions/download-artifact@v2
        with:
          name: px4_msgs
          path: bin
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Upload to Artifactory
        env:
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          BUILD_NAME: px4-msgs
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          for pkg in bin/*.deb
          do
            pkg_name=$(basename $pkg)
            jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                       --target-props COMMIT="$GITHUB_SHA" \
                       --build-name "$BUILD_NAME" \
                       --build-number "$GITHUB_SHA" \
                       "$pkg" \
                       "$ARTIFACTORY_REPO/$pkg_name"
          done
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
